import type { NoteItem } from "../types";

const seventhChords: Record<string, NoteItem[]> = {
  Major7: [
    { id: 0, label: "I" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: 2, label: "III" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: 4, label: "V" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: 6, label: "VII" },
  ],
  Dominant7: [
    { id: 0, label: "I" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: 2, label: "III" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: 4, label: "V" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: 6, label: "bVII" },
    { id: -1, label: "" },
  ],
  Minor7: [
    { id: 0, label: "i" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: 2, label: "iii" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: 4, label: "v" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: 6, label: "vii°" },
    { id: -1, label: "" },
  ],
  MinorMajor7: [
    { id: 0, label: "i" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: 2, label: "iii" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: 4, label: "v" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: 6, label: "VII" },
  ],
  HalfDiminished7: [
    { id: 0, label: "i" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: 2, label: "iii°" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: 4, label: "v" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: 6, label: "vii°" },
    { id: -1, label: "" },
  ],
  Diminished7: [
    { id: 0, label: "i" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: 2, label: "iii°" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: 4, label: "v" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: 6, label: "vii°" },
    { id: -1, label: "" },
    { id: -1, label: "" },
  ],
};

const thirdChords: Record<string, NoteItem[]> = {
  Major3: [
    { id: 0, label: "I" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: 2, label: "III" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: 4, label: "V" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: -1, label: "" },
  ],
  Minor3: [
    { id: 0, label: "i" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: 2, label: "iii" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: 4, label: "v" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: -1, label: "" },
    { id: -1, label: "" },
  ],
};

export const scales: Record<string, NoteItem[]> = {
  Major_Scale: [
    { id: 0, label: "I" },
    { id: -1, label: "" },
    { id: 1, label: "II" },
    { id: -1, label: "" },
    { id: 2, label: "III" },
    { id: 3, label: "IV" },
    { id: -1, label: "" },
    { id: 4, label: "V" },
    { id: -1, label: "" },
    { id: 5, label: "VI" },
    { id: -1, label: "" },
    { id: 6, label: "VII" },
  ],
  Minor_Scale: [
    { id: 0, label: "i" },
    { id: -1, label: "" },
    { id: 1, label: "ii" },
    { id: 2, label: "iii" },
    { id: -1, label: "" },
    { id: 3, label: "iv" },
    { id: -1, label: "" },
    { id: 4, label: "v" },
    { id: 5, label: "vi" },
    { id: -1, label: "" },
    { id: 6, label: "vii" },
    { id: -1, label: "" },
  ],
};

export const pitches = {
  ...scales,
  ...thirdChords,
  ...seventhChords,
};
